### ISSUE TITLE
DatasourceError: Plugin.unavailable

### ISSUE THREAD

**Issue by tangkong** [sasaki77/archiverappliance-datasource#144]
**Describe the bug**
We get sporadic errors where grafana reports that the datasource plugin is unavailable.  The error raises an exception/error and triggers a notification to be sent as in the screenshot below.  These errors are sporadic, and alerts will often oscillate between "Normal" and "Error" status, even though data has 

I apologize if this description is somewhat vague.  I haven't been able find settings that prevent this error from occurring, and our logs have not elucidated anything for us.  The time range of the alert does not seem to affect the error rate.

**To Reproduce**
(I'll share one of our alert configurations, but there were many that saw this error)
State history showing oscillation between "normal" and "error" state
![image](https://user-images.githubusercontent.com/35379409/229182669-f6775fef-cce7-45fb-8265-439fa1bb50ab.png)
A variety of queries showing that the query can return real values that evaluate to normal
![image](https://user-images.githubusercontent.com/35379409/229183153-b8d711bd-dadb-4e84-b0c6-87e533eb2493.png)
The resulting error notifications
![image](https://user-images.githubusercontent.com/35379409/229178143-ccff428b-9787-4f6e-8968-049525be0d77.png)

**Expected behavior**
We'd like for plugin.unavailable errors to not occur 😄 

**Desktop (please complete the following information):**
 - OS: rhel-7
 - Browser: firefox, chrome

**Comment by sasaki77** [comment]
Thank you for reporting this. I'm afraid I haven't seen this error. Could you provide the following information? It might help me to solve this issue.

- Grafana server version
- AA datasource plugin version
- Logs related to this issue in `/var/log/grafana/grafana.log`

**Comment by tangkong** [comment]
Sure thing:
* Grafana: v9.3.6
* AA: 1.3.5

I do not currently have access to the logs, but will work on that now.  Thanks for the help!

**Comment by tangkong** [comment]
We tried installing an updated plugin on our dev server, and replaced the `plugin.unavailable` errors with some slightly different errors...  
* grafana: 9.4.7
* AA: 1.5.0

Similar to before, the errors are intermittent.  In some cases I can see archiver data without error
![image](https://user-images.githubusercontent.com/35379409/230160811-60b5ed34-2e94-4b45-98fa-47c6f4cf8fe3.png)

but in other cases I get a struct-unpack error.
![Screenshot 2023-04-05 at 10 51 19 AM](https://user-images.githubusercontent.com/35379409/230162878-84bc3606-a1c7-440e-a6d7-4ee152a720d1.png)

In this grafana instance, the error shows up in the dashboard panel as well
![Screenshot 2023-04-05 at 10 50 21 AM](https://user-images.githubusercontent.com/35379409/230162727-d1b86e78-4c79-4da9-a1b1-9ff783338a4c.png)

I've verified that this behavior is not isolated to a specific PV, and also occurs for the mean operator.  The logs don't seem to have any additional information aside from the error message shown in the screenshots.  I have not yet observed the `plugin.unavailable` error we see on our prod instance

Thanks again for the help!

**Comment by sasaki77** [comment]
Thank you for your detailed report! I'm not sure why, but Grafana said that it couldn't parse the requested query. This error only occurs for alerting query, right? I'm wondering if this error also occurs for the query from the dashboard panel.

**Comment by tangkong** [comment]
Sorry for not being clear, the last screenshot was actually a view of the dashboard panel, not the alerting query.

**Comment by sasaki77** [comment]
One thing I noticed is that your Grafana might try to parse `datasource` from query. However, the original plugin codes have no `datasource` field for ArchiverQueryModel.

The original codes are available from [archiverappliance-datasource/models.go](https://github.com/sasaki77/archiverappliance-datasource/blob/ee82057c0f4355e939c5ef57ab9f565ab4b163dd/pkg/models/models.go).

I tried adding the `datasource` field as a string and Grafana returned a similar error.
Unfortunately, I can't reproduce this error in the alerting query.

```go
type ArchiverQueryModel struct {
	// It's not apparent to me where these two originate from but they do appear to be necessary
	Format    string      `json:"format"`
	Constant  json.Number `json:"constant"`  // I don't know what this is for yet
	QueryText string      `json:"queryText"` // deprecated

	// Parameters added in AAQuery's extension of DataQuery
	Target       string                         `json:"target"`       //This will be the PV as entered by the user, or regex searching for PVs
	Alias        string                         `json:"alias"`        // What to refer to the data as in the table - I think this only for the frontend rn
	AliasPattern string                         `json:"aliasPattern"` // use for collecting a large number of returned values
	Operator     string                         `json:"operator"`     // ?
	Regex        bool                           `json:"regex"`        // configured by the user's setting of the "Regex" field in the panel
	Functions    []FunctionDescriptorQueryModel `json:"functions"`    // collection of functions to be applied to the data by the archiver
	Datasource   string                         `json:"datasource"`
```

![Pasted image 20230406113058](https://user-images.githubusercontent.com/6987021/230259872-af6369d0-56e4-4fd6-8bdd-9320bad9172c.png)

Do you have any idea about this?

**Comment by sasaki77** [comment]
I have confirmed that ArchiverQueryModel has the `datasource` field in v1.3.4 or earlier. Could you check if the older version is still running or not?

**Comment by sasaki77** [comment]
I found the issue (#76) that mentions "json: cannot unmarshal" error.

**Comment by tangkong** [comment]
Argh sorry, I thought I confirmed the server restarted and AA 1.5 was running, but checking again it appears 1.3 is currently active.  I'll revisit
