### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by sasaki77** [sasaki77/archiverappliance-datasource#29]
- [x] Update documentations
- [x] Update CHANGELOG.md
- [x] Update plugin version to 1.3.0

**Comment by sasaki77** [comment]
I'm ready to release 1.3.0.
@n-wbrown Are there anything we should do before release it?

**Comment by n-wbrown** [comment]
I think we're ready to go for 1.3.0! 

Sorry the patch for the "values" bug has taken me a little longer than planned. I'll have it soon.

**Comment by sasaki77** [comment]
Releasing 1.3.0 is completed.
I really appreciate your efforts! 

If there're any problems, please let me know.
