### ISSUE TITLE
Release 1.3.2

### ISSUE THREAD

**Issue by sasaki77** [sasaki77/archiverappliance-datasource#51]
- [x] Update documentations
- [x] Update CHANGELOG.md
- [x] Update plugin version to 1.3.2

**Comment by sasaki77** [comment]
@n-wbrown Are there any updates before releasing 1.3.2?

**Comment by n-wbrown** [comment]
Hello @sasaki77, I think releasing now is a good idea. The next feature I have planned is waveform support for the backend but that will take me a bit longer to implement.
